### ISSUE TITLE
扩展显示“无法读取或更改网站的数据”

### ISSUE THREAD

**Issue by tomatomash** [Ref-rain/course-evaluation#1]
扩展显示“无法读取或更改网站的数据”，在加载了的情况下，评价也没有自动勾选上
在cent和chrome浏览器都试了试，一样没有效，求助
![2020-06-09_151225](https://user-images.githubusercontent.com/43887440/84118298-615b1780-aa65-11ea-9b7a-566f171b671a.jpg)
![2020-06-09_152535](https://user-images.githubusercontent.com/43887440/84118369-7c2d8c00-aa65-11ea-876d-32b4580ce83c.jpg)

**Comment by steeellar** [comment]
已解决，是因为课程网站从https变成了http。
